# 급여 / 비급여 의약품 연령금기 비교 분석 플랫폼

In [27]:
import pandas as pd
from sqlalchemy import create_engine, text
import os

BASE_DIR = os.getcwd()
BASE_DIR

'c:\\Users\\Administrator\\bigdata2026\\fastapi\\KIDS_Drug_Safety'

In [28]:
DATA_PATH = os.path.join(BASE_DIR, 'input', 'KIDS_Age_Contraindications_raw.csv')
DATA_PATH

'c:\\Users\\Administrator\\bigdata2026\\fastapi\\KIDS_Drug_Safety\\input\\KIDS_Age_Contraindications_raw.csv'

In [29]:
OUTPUT_PATH = os.path.join(BASE_DIR, 'output', 'KIDS_Age_Contraindications_final.csv')
OUTPUT_PATH

'c:\\Users\\Administrator\\bigdata2026\\fastapi\\KIDS_Drug_Safety\\output\\KIDS_Age_Contraindications_final.csv'

In [30]:
DB_URL = 'postgresql://postgres:1234@localhost:5432/KIDS_Age_Contraindicationsdb'

In [31]:
df_raw = pd.read_csv(DATA_PATH, encoding='cp949')
df_raw.head()

,성분명,성분코드,제품코드,제품명,업체명,특정연령,특정연령단위,급여구분,공고번호,공고일자,상세정보
0,"lidocaine, prilocaine",661200CCM,644801157,아네스크림_(20g),태극제약(주),3,개월 이하,비급여,20110227,2011-11-24,흡수에 대한 자료가 불완전하므로 소아의 생식기 점막에는 적용하지 말 것. 메트헤모글...
1,"lidocaine, prilocaine",661300CCM,641501112,엠투카인크림_(30g),맥널티제약(주),3,개월 이하,비급여,20110227,2011-11-24,흡수에 대한 자료가 불완전하므로 소아의 생식기 점막에는 적용하지 말 것. 메트헤모글...
2,"lidocaine, prilocaine",661300CCM,654303773,엠에스크림_(30g),오스틴제약(주),3,개월 이하,비급여,20110227,2011-11-24,흡수에 대한 자료가 불완전하므로 소아의 생식기 점막에는 적용하지 말 것. 메트헤모글...
3,"lidocaine, prilocaine",661300CCM,658202362,제이프로크림_(30g),(주)비보존제약,3,개월 이하,비급여,20110227,2011-11-24,흡수에 대한 자료가 불완전하므로 소아의 생식기 점막에는 적용하지 말 것. 메트헤모글...
4,"lidocaine, prilocaine",661300CCM,679800302,마네신크림_(30g),(주)티디에스팜,3,개월 이하,비급여,20110227,2011-11-24,흡수에 대한 자료가 불완전하므로 소아의 생식기 점막에는 적용하지 말 것. 메트헤모글...

In [32]:
df_raw.shape

(3006, 11)

In [33]:
for i, col in enumerate(df_raw.columns):
    print(f'[{i}] {col}')

[0] 성분명
[1] 성분코드
[2] 제품코드
[3] 제품명
[4] 업체명
[5] 특정연령
[6] 특정연령단위
[7] 급여구분
[8] 공고번호
[9] 공고일자
[10] 상세정보

In [34]:
df_raw.dtypes

성분명         str
성분코드        str
제품코드      int64
제품명         str
업체명         str
특정연령      int64
특정연령단위      str
급여구분        str
공고번호      int64
공고일자        str
상세정보        str
dtype: object

In [35]:
null_counts = df_raw.isnull().sum()
if null_counts.any():
    print('결측치 발견')
    print(null_counts[null_counts > 0])
else:
    print('결측치 없음')

결측치 발견
상세정보    641
dtype: int64

In [36]:
df_raw[df_raw['상세정보'].isnull()]

,성분명,성분코드,제품코드,제품명,업체명,특정연령,특정연령단위,급여구분,공고번호,공고일자,상세정보
114,Udenafil,553404ATB,642507050,자이데나정75밀리그램(유데나필)_(75mg/1정),동아에스티(주),18,세 이하,비급여,20090300,2009-12-03,NaN
329,polystyrene sulfonate calcium,215430ASS,657401371,케이로우현탁액(폴리스티렌설폰산칼슘)_(5g/20mL),(주)퍼슨,1,개월 미만,급여,20070030,2007-04-11,NaN
330,polystyrene sulfonate calcium,215430ASS,664101341,카슈트현탁액(폴리스티렌설폰산칼슘)_(5g/20mL),디아이디바이오(주),1,개월 미만,급여,20070030,2007-04-11,NaN
331,ketoprofen,179734COM,647800703,시푸로겔3%(케토프로펜)_(3g/100g),삼진제약(주),15,세 미만,급여,20110227,2011-11-24,NaN
332,ketoprofen,179735CCM,645601701,케바논겔(케토프로펜)_(0.9g/30g),대화제약(주),15,세 미만,급여,20110227,2011-11-24,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2679,dioctahedral smectite,146431ASS,645700121,다이톱현탁액(디옥타헤드랄스멕타이트)_(3g/20mL),삼아제약(주),24,개월 미만,급여,20200130,2020-12-28,NaN
2680,dioctahedral smectite,146431ASS,671803431,포타겔현탁액(디옥타헤드랄스멕타이트)_(3g/20mL),대원제약(주),24,개월 미만,급여,20200130,2020-12-28,NaN
2681,dioctahedral smectite,146432ASS,641607481,스타빅현탁액(디옥타헤드랄스멕타이트)_(75g/500mL),(주)대웅제약,24,개월 미만,급여,20200130,2020-12-28,NaN
2682,dioctahedral smectite,146432ASS,645700122,다이톱현탁액(디옥타헤드랄스멕타이트)_(75g/500mL),삼아제약(주),24,개월 미만,급여,20200130,2020-12-28,NaN
2683,dioctahedral smectite,146432ASS,671803433,포타겔현탁액(디옥타헤드랄스멕타이트)_(75g/500mL),대원제약(주),24,개월 미만,급여,20200130,2020-12-28,NaN

In [37]:
df_save = df_raw[['제품명', '급여구분', '특정연령','특정연령단위', '업체명']]
df_save.head()

            제품명 급여구분  특정연령 특정연령단위       업체명
0   아네스크림_(20g)  비급여     3  개월 이하   태극제약(주)
1  엠투카인크림_(30g)  비급여     3  개월 이하  맥널티제약(주)
2   엠에스크림_(30g)  비급여     3  개월 이하  오스틴제약(주)
3  제이프로크림_(30g)  비급여     3  개월 이하  (주)비보존제약
4   마네신크림_(30g)  비급여     3  개월 이하  (주)티디에스팜

In [38]:
df_save = df_save.dropna()

print(df_save.shape)

(3006, 5)

In [39]:
dr_save = df_save.drop_duplicates()
print(df_save.shape)

(3006, 5)

In [40]:
df_save["제품명"] = df_save["제품명"].str.strip()
df_save["급여구분"] = df_save["급여구분"].str.strip()
df_save["업체명"] = df_save["업체명"].str.strip()
df_save["특정연령"] = df_save["특정연령"].astype(str).str.strip()
df_save["특정연령단위"] = df_save["특정연령단위"].astype(str).str.replace('\n', '').str.strip()

In [41]:
df_save.sample(6)

,제품명,급여구분,특정연령,특정연령단위,업체명
1712,리나치올시럽5%(L-카르보시스테인)(수출명:HyundiolSyrup5%)_(50g/...,급여,24,개월 미만,현대약품(주)
487,명문구연산펜타닐주사_(0.785mg/10mL/앰플),급여,2,세 미만,명문제약(주)
1310,삼천당두타스테리드연질캡슐0.5밀리그램_(0.5mg/1캡슐),급여,18,세 미만,삼천당제약(주)
585,리메이트정(탈니플루메이트)_(0.37g/1정),급여,12,세 이하,(주)동구바이오제약
1991,헤파두스플러스연질캡슐(밀크시슬열매건조엑스)_(0.35g/1캡슐),비급여,12,세 이하,조아제약(주)
1603,맥시트롤안연고_(3.5g),급여,4,주 미만,한국노바티스(주)

In [42]:
result_list = []

for index in df_save.index:
    age = df_save.loc[index, '특정연령']
    unit = df_save.loc[index, '특정연령단위']
    
    age = float(age) 
    
    if '개월' in str(unit):
        result_list.append("영유아")
    else:
        if age <= 3:
            result_list.append("영유아")
        elif age <= 12:
            result_list.append("소아")
        elif age <= 18:
            result_list.append("청소년")
        elif age <= 65:
            result_list.append("고령자")
        else:
            result_list.append("기타")

df_save["금기연령층"] = result_list
df_save.head()

            제품명 급여구분 특정연령 특정연령단위       업체명 금기연령층
0   아네스크림_(20g)  비급여    3  개월 이하   태극제약(주)   영유아
1  엠투카인크림_(30g)  비급여    3  개월 이하  맥널티제약(주)   영유아
2   엠에스크림_(30g)  비급여    3  개월 이하  오스틴제약(주)   영유아
3  제이프로크림_(30g)  비급여    3  개월 이하  (주)비보존제약   영유아
4   마네신크림_(30g)  비급여    3  개월 이하  (주)티디에스팜   영유아

In [43]:
df_save.sample(6)

,제품명,급여구분,특정연령,특정연령단위,업체명,금기연령층
174,본비바정150밀리그램(이반드론산나트륨일수화물)_(0.16875g/1정),급여,18,세 이하,제일약품(주),청소년
2349,토피렌정100밀리그램(토피라메이트)_(0.1g/1정),비급여,2,세 미만,(주)라이트팜텍,영유아
696,엘트라셋정_(1정),급여,12,세 미만,(주)인트로바이오파마,소아
326,신일오플록사신정(수출명:FOCINATTab.)_(0.1g/1정),급여,18,세 이하,신일제약(주),청소년
2291,토피탑정100밀리그램(토피라메이트)_(0.1g/1정),비급여,2,세 미만,에이치엘비제약(주),영유아
1295,두타반연질캡슐(두타스테리드)_(0.5mg/1캡슐),급여,18,세 미만,동아에스티(주),청소년

In [44]:
df_save.dtypes

제품명       str
급여구분      str
특정연령      str
특정연령단위    str
업체명       str
금기연령층     str
dtype: object

In [45]:
df_save["급여구분"].value_counts()

급여구분
급여     2171
비급여     835
Name: count, dtype: int64

In [46]:
df_save["업체명"].nunique()

237

In [47]:
df_save["금기연령층"].value_counts()

금기연령층
청소년    1361
소아      892
영유아     719
기타       20
고령자      14
Name: count, dtype: int64

In [48]:
def save_to_postgresql(df, db_url, table_name):
    df_save = df.copy()

    for col in df_save.columns:
        if pd.api.types.is_string_dtype(df_save[col]):
            df_save[col] = df_save[col].astype(str)

    engine = create_engine(db_url)

    with engine.connect() as conn:
        version = conn.execute(text('SELECT version();')).fetchone()[0]
        print('PostgreSQL 연결 성공')
        print(version[:80] + '...')

        df_save.to_sql(
            name=table_name,
            con=engine,
            if_exists='replace',
            index=False,
            chunksize=1000,
            method= 'multi',
        )

        with engine.connect() as conn:
            saved_count = conn.execute(text(f'SELECT COUNT(*) FROM "{table_name}";')).fetchone()[0]
    
    print(f'저장 완료 {saved_count}')
    print(f'DB : KIDS_Age_Contraindicationsdb / table: {table_name}')

In [49]:
TABLE_NAME = 'KIDS_Age_Contraindications_final'

In [50]:
save_to_postgresql(df_save, DB_URL, TABLE_NAME)

PostgreSQL 연결 성공
PostgreSQL 17.10 on x86_64-windows, compiled by msvc-19.44.35227, 64-bit...
저장 완료 3006
DB : KIDS_Age_Contraindicationsdb / table: KIDS_Age_Contraindications_final

In [51]:
df_save.to_csv(OUTPUT_PATH, encoding='utf-8-sig', index=False)

print('CSV 저장 완료')
print(f'경로: {OUTPUT_PATH}')
print(f'크기: {len(df_save):,}행 x {len(df_save.columns)}열')

CSV 저장 완료
경로: c:\Users\Administrator\bigdata2026\fastapi\KIDS_Drug_Safety\output\KIDS_Age_Contraindications_final.csv
크기: 3,006행 x 6열

In [52]:
print('=' * 80)
print('급여 / 비급여 의약품 연령금기 비교 분석 결과')
print('=' * 80)

print('데이터 출처 : 식품의약품안전처 DUR 품목정보')
print(f'수집건수 : {len(df_save)}건') 
print(f'컬럼 수 : {len(df_save.columns)}개')
print(f'CSV 저장 위치 : {OUTPUT_PATH}')
print(f'DB 저장 위치 : bigdatatestdb.{TABLE_NAME}')

print('=' * 60)
print('급여구분 현황')
print(df_save['급여구분'].value_counts())

print('=' * 60)
print('금기연령층 현황')
print(df_save['금기연령층'].value_counts())

print('=' * 60)
print(f'업체 수 : {df_save["업체명"].nunique()}개')

print('=' * 60)
print(f'특정연령 범위 : {df_save["특정연령"].min()} ~ {df_save["특정연령"].max()}') 

print('=' * 80)
print('데이터 저장 완료')
print('=' * 80)

================================================================================
급여 / 비급여 의약품 연령금기 비교 분석 결과
================================================================================
데이터 출처 : 식품의약품안전처 DUR 품목정보
수집건수 : 3006건
컬럼 수 : 6개
CSV 저장 위치 : c:\Users\Administrator\bigdata2026\fastapi\KIDS_Drug_Safety\output\KIDS_Age_Contraindications_final.csv
DB 저장 위치 : bigdatatestdb.KIDS_Age_Contraindications_final
============================================================
급여구분 현황
급여구분
급여     2171
비급여     835
Name: count, dtype: int64
============================================================
금기연령층 현황
금기연령층
청소년    1361
소아      892
영유아     719
기타       20
고령자      14
Name: count, dtype: int64
============================================================
업체 수 : 237개
============================================================
특정연령 범위 : 1 ~ 80
================================================================================
데이터 저장 완료
================================================================================